version: '3.8'
services:
  mysql:
    image: mysql:8-oracle
    container_name: mysqldb
    tty: true
    # container_name: mysql-test-project
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d # 初期化データを実行
      - test-project-mysql-data:/var/lib/mysql # 永続化用のvolumeと紐付け
      - ./db/mysql/logs:/var/log/mysql # ログ出力用のディレクトリ
    environment:
      # MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: test-db
      MYSQL_DATABASE: mydb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
      NEXT_PUBLIC_API_ROOT: http://localhost:3000
      # MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer-test-project
    ports:
      - 8080:8080
    depends_on:
      - mysql

  prisma-studio:
    # container_name: prisma-studio-test-project
    image: node:16.4.2
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - '3000:3000'
    tty: true
    # command: /bin/sh -c "npm install"
    depends_on:
      - mysql

# mysqlの永続化用名前付きvolume
volumes:
  test-project-mysql-data: