version: '3.8'
services:
  mysql:
    image: mysql:8-oracle
    container_name: mysql-test-project
    volumes:
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d # 初期化データを実行
      - test-project-mysql-data:/var/lib/mysql # 永続化用のvolumeと紐付け
      - ./db/mysql/logs:/var/log/mysql # ログ出力用のディレクトリ
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-db
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer-test-project
    ports:
      - 8080:8080
    depends_on:
      - mysql

  prisma-studio:
    container_name: prisma-test-project
    image: node:16.4.2
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - '5555:5555'
    tty: true
    command: /bin/sh -c "npm run docker-prisma-studio"
    depends_on:
      - mysql

# mysqlの永続化用名前付きvolume
volumes:
  test-project-mysql-data: